sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 111
  alioss:
    access-key-id: LTAI5tFRFWNt5unecMwXJreA
    endpoint: oss-cn-beijing.aliyuncs.com
    bucket-name: sky-lhf
    access-key-secret: K5mBA21mnYFgREjuESy7mp5uxGINNQ
  redis:
    host: localhost
#    password: 111
    port: 6379
    database: 10
  wechat:
    appid: wx6f96e80e4c5e7982
    secret: 75e14c17ea0f7b159bcd6a75efbde46e